# Persistent Volume Claims using Azure managed premium disks
# Storage class 'managed-premium' should be created (see 01-infrastructure-setup.md)

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 20Gi  # Increased for production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi  # Increased for production
---
# Shared storage for static files and media
# Note: For ReadWriteMany, consider Azure Files (azurefile-csi storage class)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-shared-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteOnce  # For RWO, only one pod can mount. For RWX, use azurefile-csi
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi  # Increased for production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-results-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi  # Increased for production

