# Persistent Volume Claims using Azure managed premium disks
# AKS default storage class 'managed-csi' or 'default' provides premium disks
# For custom storage class, use: managed-csi-premium

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  # AKS default premium storage class
  resources:
    requests:
      storage: 20Gi  # Increased for production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  # AKS default premium storage class
  resources:
    requests:
      storage: 5Gi  # Increased for production
---
# Shared storage for static files and media
# Using Azure Files (azurefile-csi) for ReadWriteMany to allow multiple pods to mount
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-shared-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteMany  # Required for multiple pods (frontend + backend) to mount simultaneously
  storageClassName: azurefile-csi  # Azure Files supports RWX access mode
  resources:
    requests:
      storage: 10Gi  # Increased for production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-results-pvc
  namespace: packamal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  # AKS default premium storage class
  resources:
    requests:
      storage: 50Gi  # Increased for production

