apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: packamal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          # Reuses the backend image; runs Celery Beat for periodic task scheduling.
          image: packamalacr.azurecr.io/packamal-backend:latest
          imagePullPolicy: Always  # Use Always for production or specific tags
          envFrom:
            - configMapRef:
                name: packamal-config
            - secretRef:
                name: packamal-secrets
          # Override the image ENTRYPOINT to run Celery Beat.
          # Still waits for Postgres and Redis before starting.
          command: ["/bin/sh", "-c"]
          args:
            - |
              until nc -z database 5432; do
                echo "Waiting for database..."
                sleep 0.5
              done
              until nc -z redis 6379; do
                echo "Waiting for Redis..."
                sleep 0.5
              done
              exec celery -A packamal beat -l info
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

