apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-serviceaccount
  namespace: packamal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-job-creator
  namespace: packamal
rules:
  # Allow creating, getting, listing, and deleting Jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  # Allow getting and listing Pods (for job status monitoring)
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "delete"]
  # Optional: support clusters with custom admission (e.g. OpenShift SCC / OPA)
  # so that this service account can be granted or updated to use privileged
  # security constraints if the cluster enforces them.
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-job-creator-binding
  namespace: packamal
subjects:
  - kind: ServiceAccount
    name: backend-serviceaccount
    namespace: packamal
roleRef:
  kind: Role
  name: backend-job-creator
  apiGroup: rbac.authorization.k8s.io

