# Generated by Django 5.2.9 on 2025-12-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this API key', max_length=100)),
                ('key', models.CharField(help_text='The actual API key', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_hour', models.IntegerField(default=100, help_text='Maximum requests per hour')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('package_version', models.CharField(max_length=20)),
                ('ecosystem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDynamicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('report', models.JSONField(default=dict)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_dynamic_analysis', to='package_analysis.package')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.JSONField(default=list)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_source', to='package_analysis.package')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTyposquatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typosquatting_candidates', models.JSONField(default=list)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_typosquatting', to='package_analysis.package')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.CharField(help_text='Package URL submitted for analysis', max_length=500)),
                ('package_name', models.CharField(blank=True, max_length=200)),
                ('package_version', models.CharField(blank=True, max_length=100)),
                ('ecosystem', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_category', models.CharField(blank=True, help_text='Category of error (e.g., docker_error, timeout_error, analysis_error)', max_length=50)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error information including stderr, stdout, etc.')),
                ('download_url', models.URLField(blank=True, help_text='URL to download the analysis report JSON file', null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, help_text='Position in the analysis queue', null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority level (higher number = higher priority)')),
                ('queued_at', models.DateTimeField(blank=True, help_text='When the task was added to the queue', null=True)),
                ('timeout_minutes', models.PositiveIntegerField(default=30, help_text='Timeout in minutes for this task')),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID if running', max_length=100, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last heartbeat from running container', null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='package_analysis.apikey')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package_analysis.reportdynamicanalysis')),
            ],
            options={
                'indexes': [models.Index(fields=['purl'], name='package_ana_purl_c7b6b7_idx'), models.Index(fields=['status', 'created_at'], name='package_ana_status_adc3e7_idx'), models.Index(fields=['api_key', 'created_at'], name='package_ana_api_key_3af360_idx'), models.Index(fields=['status', 'queue_position'], name='package_ana_status_0f87a3_idx'), models.Index(fields=['priority', 'queued_at'], name='package_ana_priorit_d7d99d_idx'), models.Index(fields=['status', 'started_at'], name='package_ana_status_9ff0e2_idx'), models.Index(fields=['container_id'], name='package_ana_contain_07c0ee_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('api_key', 'idempotency_key'), name='unique_api_key_idempotency_key')],
            },
        ),
    ]
