# Generated by Django 5.2.10 on 2026-01-22 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purl', models.CharField(db_index=True, max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, default='queued', max_length=20)),
                ('job_id', models.CharField(blank=True, db_index=True, help_text='K8s Job Name', max_length=100, null=True)),
                ('report_blob_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='package_analysis.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('package_version', models.CharField(max_length=100)),
                ('ecosystem', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('package_name', 'package_version', 'ecosystem')},
            },
        ),
    ]
