# Generated by Django 5.2.9 on 2025-12-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, help_text='K8s job ID for tracking', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['job_id'], name='package_ana_job_id_05ba9b_idx'),
        ),
    ]
