# Generated by Django 5.2.9 on 2025-12-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0002_analysistask_job_id_alter_analysistask_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysistask',
            name='unique_api_key_idempotency_key',
        ),
        migrations.RemoveField(
            model_name='analysistask',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='time',
        ),
    ]
