# Generated by Django 5.2.9 on 2026-01-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package_analysis", "0004_analysistask_result_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdynamicanalysis",
            name="report_location",
            field=models.TextField(
                blank=True,
                help_text="Location (path or URL) of the stored report artifact",
                null=True,
            ),
        ),
    ]


