apiVersion: v1
kind: Secret
metadata:
  name: packamal-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "rock-beryl-say-devices"
  SECRET_KEY: "#d%!dmd7v+nfg9=(%y@v(c_lfpja02*#0&5ohk=42bljrl99y!"
  INTERNAL_API_TOKEN: "Rthj7yHEBt9Fp3A9BHfmfsDcuIPItWOnSkRNy4euus5825cAd8ho4J4CRLfOmCM2"
  AUTH_TOKEN: "qe&d%!9ijh7v+nfg9=(%y@v(324ddja02*#0&5oh$$42bljrl99y!"
